name: wpm
description: Well.. Simple Package Manager (zip-based)
version: 2.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  path: ^1.9.0

# No executables section; compiled via build scripts
